[[LERC]]
arch = "aarch64"
git-tree-sha1 = "9fe5813e6a8dc30c8d2d61b494c8d0250437353f"
os = "macos"

    [[LERC.download]]
    sha256 = "7e9d898a01233228928fe7e59102391c561e5ac2180836bec1c886bd07e0c077"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.aarch64-apple-darwin.tar.gz"
[[LERC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb2b46d11d5ff6045fc358d85b4f6e4cea6dee0d"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "53a5e7b5a9251cad0b802d578b966661989edc064916c46bcd233fb66f77ab45"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[LERC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6664bfc603d6b76151aa92b8961914749141869"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "c440e87de58b95dfd078f22af356421dbaa3b140bfd8ee35ce44c5b8c0be3fc3"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[LERC]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6689bed62438b056107d1268de72ec96394ba00"
libc = "musl"
os = "linux"

    [[LERC.download]]
    sha256 = "2f4c467d45bf3493e72567da03e2665f784f81ad46e992e943255b1d7baeac7c"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[LERC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5d1119f112d7ef75b8fd02dfb71961cc1b7eac2"
libc = "musl"
os = "linux"

    [[LERC.download]]
    sha256 = "873f64d7232bcf8689bc34cb6d4d5da6e27b8bc6e25b0273ad11250560ecf3bb"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[LERC]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1db19a3e4cbb23ddeb939a6207616cffb01cb5e3"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "0e55d16656972c09a171cee61eb7558943afe786cc2e6f0f38cefead19dff88e"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LERC]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7daf95444995ce552f42e61b70386a809bc8b77"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "f1368a5bc81d1cc31afca6a242e55182c52b16ee8613c5953da6987c3def6a35"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LERC]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4984cee59927d7410bcc42f50b5896ce96c836ae"
libc = "musl"
os = "linux"

    [[LERC.download]]
    sha256 = "d2ae1f1234b174cc14707a71fda49e1612c84414c22eb27609968a176a2fd0fa"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LERC]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22f1b87ce6aca8b0739d2d47e9ab3f650dd3c86e"
libc = "musl"
os = "linux"

    [[LERC.download]]
    sha256 = "50cf5ff3f4ac56a28a45a3598a9e05330a83a65b3da2da7971c803e39ae12fdf"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LERC]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c86023f770795016ecadce0bbe060d391cc64d05"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "b5c81998f67975ba8f3fa70a1e53cfd1eaac359bfd3832c919cfcd44c3e79056"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LERC]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1aa55ce7a8a1f8f1d7f8be071e4ff3fca523e838"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "1188ffe94db5dd78129b65a8f7e8c7f226ed1005068cc5b3970688c6067110e3"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LERC]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b4adb5c78a2dcfd800744cd306d46d40b1befda"
libc = "musl"
os = "linux"

    [[LERC.download]]
    sha256 = "9fd2669b5886175130a047e6a3ebca3138a1bb3aa12230f58755ed10d8e85dd7"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LERC]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f348927c79830a5785aa055560beb74df59fc8e"
libc = "musl"
os = "linux"

    [[LERC.download]]
    sha256 = "06021872543a7290fc0efd4ff9a4067922f3a6b33356acd39e965bb0832f5d07"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LERC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a912ebb2f7e8f3879f54f091227b8dbaecb95f56"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "f21419778cda13bdec600498bbb6d844f077c0308fd35920b04bdb8110677f1b"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.i686-linux-gnu-cxx03.tar.gz"
[[LERC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b74b6d27aa1f9ea678935a4c03f12c56cbe1685"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "d1e19890ffc3c76578b3dfe7dd6980a5e5971b6f2b479ee50ed28fbdee39009d"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.i686-linux-gnu-cxx11.tar.gz"
[[LERC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f8344cb201a6a0a3f04aedc4a5424b06f43fd4f"
libc = "musl"
os = "linux"

    [[LERC.download]]
    sha256 = "e1ab9148104d0a47565c0c792a27844bf3d0d9dff6391afbab797e6273836da5"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.i686-linux-musl-cxx03.tar.gz"
[[LERC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87d4136de6c62e77cf2dc676702c0dbc44f409a5"
libc = "musl"
os = "linux"

    [[LERC.download]]
    sha256 = "cb8dd4559899e0c857ee3bc3fdc28e186bd7a9b9e61d8a713994a86890ed7b35"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.i686-linux-musl-cxx11.tar.gz"
[[LERC]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "451e00e87388d9d66072d2a7cf2c4902fa8d0745"
os = "windows"

    [[LERC.download]]
    sha256 = "cf5b591e3fe4318b366d378a291a8a964a864947c0746025d77419bd99a39c80"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[LERC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b83fbcd6b6022ad0d4a154bcfaf84606cec8fb0"
os = "windows"

    [[LERC.download]]
    sha256 = "8ae8d68c5c2dd1c0c163a0f89c2c71078f415e9051e6445147fd19495aee12cd"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[LERC]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50b90b94988537a575f9254975249c80921b146c"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "8183b3f9a4ef3886cb7edad120985c7d5ab2efec126c39b34691e4dcd16d74c9"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LERC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49a07c22429c24ce8e45f1c6f8b09a2fbac2d33f"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "8c847d26684762e593cfbe8f8d83b0d582ce43b6492718634903023220d8f1ed"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LERC]]
arch = "x86_64"
git-tree-sha1 = "c2341ab63e1b4806b7e0e2eac28ff278964a3c61"
os = "macos"

    [[LERC.download]]
    sha256 = "6642775bcd1703c18bb75e087f9bad2df5f348a6ee0f7ea0f320f6ed9e79caae"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.x86_64-apple-darwin.tar.gz"
[[LERC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53011ca8942e52453c1868382b985c9cef245f06"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "bc05a7e0d0fb24429278bad49ce00aa504bd01fa3221d9c82a17ff79809d6ce2"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[LERC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbef68f6f587b5d3709af5b95701b92e3b890e4b"
libc = "glibc"
os = "linux"

    [[LERC.download]]
    sha256 = "ac3daaeb48f292e29efe85c59e02d7e99b3c40d14cea0c2b099f4c7676ee765f"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[LERC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2f9261457dc61b3c9e8d169d63c2fad22ddebf8"
libc = "musl"
os = "linux"

    [[LERC.download]]
    sha256 = "7238bf4d2efc9fe939d5f2f4882c1a6634eda4045867472eedbe54df4e48159e"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[LERC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9edc084061085f97256c0a3d9b566d5d2729af09"
libc = "musl"
os = "linux"

    [[LERC.download]]
    sha256 = "f3030c8e5d57b30db495eaa873f6cbd282d3c8f3216dea16435ec2d8ad90c00b"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[LERC]]
arch = "x86_64"
git-tree-sha1 = "73192996e61dacbc8bde13ab9845d29f05c19013"
os = "freebsd"

    [[LERC.download]]
    sha256 = "cb1adeb9493bda070a9138991ead84c0b26a3ff392ef73ebbb0724e0637e10b3"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.x86_64-unknown-freebsd.tar.gz"
[[LERC]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c79bd8257d207be3fc9ad70b7708e641c085e39e"
os = "windows"

    [[LERC.download]]
    sha256 = "f97a0d6ce1b3a4747174ded2c5af084cb325feb903b5c816206d4d7454b0a29f"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[LERC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfa50f82c74b3dc3fe4830348b33ae3641719a31"
os = "windows"

    [[LERC.download]]
    sha256 = "94dafb6b7817c9a8d8342818c8f12908f970bcca4592a201792f0869406a2fb7"
    url = "https://github.com/JuliaBinaryWrappers/LERC_jll.jl/releases/download/LERC-v4.0.0+0/LERC.v4.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
